### ISSUE TITLE
Buildicus blog has extra "blog" in url path

### ISSUE THREAD

**Issue by irms** [EditLLC/buildicus-dot-com#57]
To reproduce:

- go to buildicus.com/blog
- click on any blog title
- see the url now has an extra "blog" in the path. For visual representation:

<img width="539" alt="screenshot 2016-06-14 11 53 47" src="https://cloud.githubusercontent.com/assets/643997/16055703/37658362-3227-11e6-908a-1dc1b7f3dec0.png">

Looks like the repo got duplicated inside of the /blog/ folder perhaps?

**Comment by spriggsj** [comment]
Removed extra "blog" from Path
